OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - "localhost"

PeerOrgs:
  - Name: HospitalA
    Domain: hospitala.example.com
    EnableNodeOUs: true
    Template:
      Count: 10
      SANS:
        - localhost
    Users:
      Count: 10

  - Name: HospitalB
    Domain: hospitalb.example.com
    EnableNodeOUs: true
    Template:
      Count: 10
      SANS:
        - localhost
    Users:
      Count: 10