OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - "localhost"
          - "127.0.0.1"

PeerOrgs:
  - Name: HospitalA
    Domain: hostpitala.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: HospitalB
    Domain: hostpitalb.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1